-- Supabase PostgreSQL Schema for UniRev

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables so you can run this script safely without "already exists" errors
DROP TABLE IF EXISTS course_professors CASCADE;
DROP TABLE IF EXISTS prerequisites CASCADE;
DROP TABLE IF EXISTS program_courses CASCADE;
DROP TABLE IF EXISTS user_layouts CASCADE;
DROP TABLE IF EXISTS user_courses CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS professors CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS faculties CASCADE;
DROP TABLE IF EXISTS universities CASCADE;

-- 1. Universities
CREATE TABLE universities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- 2. Faculties
CREATE TABLE faculties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id BIGINT REFERENCES universities(id) ON DELETE CASCADE,
    name TEXT NOT NULL
);

-- 3. Departments
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id BIGINT REFERENCES faculties(id) ON DELETE CASCADE,
    name TEXT NOT NULL
);

-- 4. Courses
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    credit_hours INTEGER,
    category TEXT -- 'University Requirement', 'Faculty Requirement', etc.
);

-- 4.5. Program Courses (Many-to-Many)
CREATE TABLE program_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT REFERENCES departments(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    semester INTEGER NOT NULL,
    UNIQUE(program_id, course_id)
);

-- 5. Prerequisites
CREATE TABLE prerequisites (
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    prerequisite_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    PRIMARY KEY (course_id, prerequisite_id)
);

-- 6. Professors
CREATE TABLE professors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- 7. Course Professors (Many-to-Many)
CREATE TABLE course_professors (
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    professor_id BIGINT REFERENCES professors(id) ON DELETE CASCADE,
    PRIMARY KEY (course_id, professor_id)
);

-- 8. Users (Links to Supabase Auth implicitly or explicitly via ID later)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'student' CHECK (role IN ('student', 'admin'))
);

-- 9. Reviews
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    professor_id BIGINT REFERENCES professors(id) ON DELETE SET NULL,
    difficulty INTEGER CHECK (difficulty BETWEEN 1 AND 5),
    workload INTEGER CHECK (workload BETWEEN 1 AND 5),
    exam_difficulty INTEGER CHECK (exam_difficulty BETWEEN 1 AND 5),
    grading_fairness INTEGER CHECK (grading_fairness BETWEEN 1 AND 5),
    attendance_strictness INTEGER CHECK (attendance_strictness BETWEEN 1 AND 5),
    recommend BOOLEAN,
    advice TEXT,
    professor_feedback TEXT,
    term TEXT CHECK (term IN ('Fall', 'Spring', 'Summer')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. User Courses (Status Tracking)
CREATE TABLE user_courses (
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'not_taken' CHECK (status IN ('completed', 'in_progress', 'planned', 'not_taken')),
    PRIMARY KEY (user_id, course_id)
);

-- 11. User Layouts (Visual Map Locations)
CREATE TABLE user_layouts (
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    x REAL,
    y REAL,
    semester INTEGER,
    PRIMARY KEY (user_id, course_id)
);

-- Turn on Row Level Security (RLS) for all tables
ALTER TABLE universities ENABLE ROW LEVEL SECURITY;
ALTER TABLE faculties ENABLE ROW LEVEL SECURITY;
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE prerequisites ENABLE ROW LEVEL SECURITY;
ALTER TABLE professors ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_professors ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_layouts ENABLE ROW LEVEL SECURITY;

-- Base Policies (Public Read Access for Course Data)
DROP POLICY IF EXISTS "Public read access" ON universities;
CREATE POLICY "Public read access" ON universities FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read access" ON faculties;
CREATE POLICY "Public read access" ON faculties FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read access" ON departments;
CREATE POLICY "Public read access" ON departments FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read access" ON courses;
CREATE POLICY "Public read access" ON courses FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read access" ON program_courses;
CREATE POLICY "Public read access" ON program_courses FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read access" ON prerequisites;
CREATE POLICY "Public read access" ON prerequisites FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read access" ON professors;
CREATE POLICY "Public read access" ON professors FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read access" ON course_professors;
CREATE POLICY "Public read access" ON course_professors FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public read access" ON reviews;
CREATE POLICY "Public read access" ON reviews FOR SELECT USING (true);

-- User Specific Policies (Users can read and update their own data)
DROP POLICY IF EXISTS "Users can read own data" ON users;
CREATE POLICY "Users can read own data" ON users FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can read own layouts" ON user_layouts;
CREATE POLICY "Users can read own layouts" ON user_layouts FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own layouts" ON user_layouts;
CREATE POLICY "Users can insert own layouts" ON user_layouts FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own layouts" ON user_layouts;
CREATE POLICY "Users can update own layouts" ON user_layouts FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can read own course status" ON user_courses;
CREATE POLICY "Users can read own course status" ON user_courses FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own course status" ON user_courses;
CREATE POLICY "Users can insert own course status" ON user_courses FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own course status" ON user_courses;
CREATE POLICY "Users can update own course status" ON user_courses FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own reviews" ON reviews;
CREATE POLICY "Users can insert own reviews" ON reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
